import type { CombatLoadout } from "./combat-loadout.ts";
import type { HuntBotSpellBook } from "./hunt-bot-spell-book.ts";
import type { HuntRosterBotSeed } from "./hunt-roster-bot.ts";

export type HuntBattleInit = Readonly<{
  fightId: string;
  accessKey: string;
  accountId: number;
  heroId: number;
  heroNick: string;
  heroLevel: number;
  heroKind: number;
  heroMp: number;
  heroMaxMp: number;
  botArtikulId: number;
  botFightId: number;
  botNick: string;
  botLevel: number;
  botAvatar: string;
  botSk: string;
  botBody: string;
  playerHp: number;
  playerMaxHp: number;
  botMaxHp: number;
  arena: string;
  areaId: string;
  startedAt: Date;
  loadout: CombatLoadout;
  heroStrength: number;
  botStrength: number;
  botSpellBook: HuntBotSpellBook;
  purpose: "hunt" | "quest";
  extraEnemies: readonly HuntRosterBotSeed[];
  allies: readonly HuntRosterBotSeed[];
  chatWin: string;
  chatLose: string;
}>;
