export function buildFlashVars(
  user: Readonly<{ id: number; nick: string }>,
  serverTime = Math.floor(Date.now() / 1000),
): string {
  const params: Record<string, string> = {
    swfPath: "images/swf/",
    unityPath: "images/unity/",
    artifactPath: "images/data/artifacts/",
    artifactBigPath: "images/data/artifacts_big/",
    avatarPath: "images/data/avatars/",
    avatarBigPath: "images/data/avatars_big/",
    assistantPath: "images/data/assistants/",
    huntBotPath: "images/data/hunt_bots/",
    npcPath: "images/data/npcs/",
    areaLinkPath: "images/data/area_links/",
    areaSwfPath: "images/data/area_swf/",
    areaPath: "images/data/area/",
    skillPath: "images/data/skill/",
    statPath: "images/data/user_stat/",
    amfPath: "amf/",
    clansPath: "images/data/clans/",
    kindPath: "images/kind/",
    localePath: "images/locale/ru/",
    soundsPath: "images/data/sounds/",
    imageAchieve: "images/data/achievements/",
    instanceMapPath: "images/data/instance_maps/",
    npcWaitingPath: "images/data/waiting/",
    frontsPath: "images/data/fronts/",
    mapPath: "images/data/maps/",
    smilesPath: "images/data/smileys/",
    petPath: "images/data/pets/",
    petSupressPath: "images/data/pets/supress/",
    premiumStatusPath: "images/data/info_premium_status/",
    unityLink: "images/unity/player.unity3d?ux=emu",
    cfgLink: "modules/cfg/links.cfg?ux=emu",
    cfgLinkUx: "images/data/links_ux.cfg?ux=emu",
    serverTime: String(serverTime),
    nick: user.nick,
    id: String(user.id),
    server_id: "1",
    forumLink: "/info/forum/",
    newsLink: "/info/news/",
    libraryLink: "/info/rating/",
    aboutLink: "/info/info/index.php",
    faqLink: "/info/info/index.php",
    smsInfo: "partner/general/sms_info.xml",
    localeCode: "ru",
    debugFlash: "0",
    recommended_flash_player_major_version: "11",
    recommended_flash_player_minor_version: "3",
    tutorialReady: "1",
    hideLogoutButton: "",
    abc_max_points: "100",
    supported_languages: "ru",
    soc_js_prefix: "emu",
    fake_hunt: "0",
  };
  return Object.entries(params)
    .map(([key, value]) => `${encodeURIComponent(key)}=${encodeURIComponent(value)}`)
    .join("&");
}
